# Generated by Django 5.1.6 on 2025-03-10 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_post_status_remove_post_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='featured',
            new_name='is_featured',
        ),
    ]
