# Generated by Django 5.1.6 on 2025-03-10 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_featured_post_is_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_featured',
            new_name='featured',
        ),
    ]
