# Generated by Django 5.1.6 on 2025-03-10 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_is_featured_post_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='featured',
        ),
    ]
